
<!-- include libraries -->

```{r, include = FALSE, echo = FALSE}

library(dplyr)
library(ggplot2)
library(here)
library(knitr)
library(kableExtra)

```

<!-- kableExtra bootstrap css 
https://haozhu233.github.io/kableExtra/bookdown/use-bootstrap-tables-in-gitbooks-epub.html
-->

```{r}

options(kableExtra.html.bsTable = TRUE)

```


<!-- knit_hook: collapse and strip white 
this is a Blake hack -->

```{r, include = FALSE, echo = FALSE}

local({
  
  hook_source <- knitr::knit_hooks$get('source')
  knitr::knit_hooks$set(source = function(x, options) {
    
    is_blank2 = function(x) {
      
      if (length(x)) all(grepl('^\\s*$', x)) else TRUE
      
    }
    
    strip_white2 = function(x, test_strip = is_blank2) {
      if (!length(x)) return(x)
      while (test_strip(x[1])) {
        x = x[-1]; if (!length(x)) return(x)
      }
      while (test_strip(x[(n <- length(x))])) {
        x = x[-n]; if (n < 2) return(x)
      }
      x
    }
    
    x <- xfun::split_lines(x)
    x <- strip_white2(x)
    x <- paste(x, sep = '', collapse = '\n')
    
    hook_source(x, options)
    
  })
  
})

```

<!-- knit_hook: collapse and print error red
super hacky, see here: https://stackoverflow.com/a/54985678/7705429
we'll need to be careful to not string four # together anywhere
--->

<script>
$(document).ready(function() {
  window.setTimeout(function() {
    $(".co:contains('####')").css("color", "red");
    var tmp = $(".co:contains('####')").text();
    $(".co:contains('####')").text(tmp.replace("####", "##"));
  }, 15);
});
</script>

```{r, include = FALSE, echo = FALSE}

local({
  
  hook_error <- knitr::knit_hooks$get("error")
  knitr::knit_hooks$set(error = function(x, options) {
    x <- paste0("##", x)
    x <- sub(" in eval(expr, envir, enclos)", "", x, fixed = TRUE)
    hook_error(x, options)
  })
  
})

```

<!-- chunk options -->

```{r, echo = FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      error = TRUE,
                      collapse = TRUE, # code and output in same block
                      fig.align = "center")

```



<!-- miscellaneous -->

```{r, include = FALSE, echo = FALSE}

set.seed(2020)

source(here("R/insert_intro.R"))

```

<!-- 
make error messages closer to base R 
https://github.com/hadley/adv-r/blob/master/common.R
looks like it doesn't work because R no longer
let's users override s3 methods, so I changed the s3 to "simpleError"
-->

```{r, echo = FALSE}

registerS3method("wrap", "simpleError", envir = asNamespace("knitr"),
  function(x, options) {
    msg <- conditionMessage(x)

    call <- conditionCall(x)
    if (is.null(call)) {
      msg <- paste0("Error: ", msg)
    } else {
      msg <- paste0("Error in ", deparse(call)[[1]], ": ", msg)
    }

    msg <- error_wrap(msg)
    knitr:::msg_wrap(msg, "error", options)
  }
)

error_wrap <- function(x, width = getOption("width")) {
  lines <- strsplit(x, "\n", fixed = TRUE)[[1]]
  paste(strwrap(lines, width = width), collapse = "\n")
}

```



