on:
  push:
     branches:
       - main
       
name: renderbook

jobs:
  bookdown:
    name: Render-Book
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown"))'
      - name: Install other packages
        run: Rscript -e 'install.packages(c("dplyr", "ggplot2", "here", "knitr", "kableExtra", "gifski"))'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE)'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/
  
# gh-action from Cecilapp/GitHub-Pages-deploy
  checkout-and-deploy:
   runs-on: ubuntu-latest
   needs: bookdown
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Download artifact
       uses: actions/download-artifact@v2
       with:
         # Artifact name
         name: _book # optional
         # Destination path
         path: _book # optional
     - name: Deploy to GitHub Pages
       uses: Cecilapp/GitHub-Pages-deploy@v3
       env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # https://github.com/settings/tokens
       with:
          email: ${{ secrets.EMAIL }}            # must be a verified email
          build_dir: _book/                      # "_site/" by default
    
 
